/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BottomNav: typeof import('./../layout/BottomNav.vue')['default']
    CategoryList: typeof import('./../views/home/CategoryList.vue')['default']
    Home: typeof import('./../views/home/Home.vue')['default']
    Layout: typeof import('./../layout/Layout.vue')['default']
    ProductList: typeof import('./../components/ProductList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShoppingCart: typeof import('./../views/ShoppingCart.vue')['default']
    UserInfo: typeof import('./../views/UserInfo.vue')['default']
  }
}
