/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AuthPage: typeof import('./../views/AuthPage.vue')['default']
    BackButton: typeof import('./../components/BackButton.vue')['default']
    BackTop: typeof import('./../components/BackTop.vue')['default']
    BottomNav: typeof import('./../layout/BottomNav.vue')['default']
    CartList: typeof import('./../views/shopcart/CartList.vue')['default']
    CategoryList: typeof import('./../views/home/CategoryList.vue')['default']
    Counter: typeof import('./../components/Counter.vue')['default']
    CounterButton: typeof import('./../components/CounterButton.vue')['default']
    FormInput: typeof import('./../components/FormInput.vue')['default']
    FornInput: typeof import('./../components/FornInput.vue')['default']
    Home: typeof import('./../views/home/Home.vue')['default']
    Layout: typeof import('./../layout/Layout.vue')['default']
    LayoutBox: typeof import('./../layout/LayoutBox.vue')['default']
    LoginPage: typeof import('./../views/LoginPage.vue')['default']
    Notification: typeof import('./../components/Notification.vue')['default']
    NotificationBox: typeof import('./../components/NotificationBox.vue')['default']
    Product: typeof import('./../views/Product.vue')['default']
    ProductList: typeof import('./../components/ProductList.vue')['default']
    ProductView: typeof import('./../views/ProductView.vue')['default']
    RegistPage: typeof import('./../views/RegistPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SeachTab: typeof import('./../views/home/SeachTab.vue')['default']
    ShoppingCart: typeof import('./../views/ShoppingCart.vue')['default']
    UserInfo: typeof import('./../views/UserInfo.vue')['default']
  }
}
